CLASS zcl_lab_12_linux_mb DEFINITION INHERITING FROM zcl_lab_11_system_mb
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_12_linux_mb IMPLEMENTATION.
ENDCLASS.
