CLASS zcl_lab_19_lion_mb DEFINITION INHERITING FROM zcl_lab_18_animal_mb
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_19_lion_mb IMPLEMENTATION.
  METHOD walk.
    rv_walk = 'The lion walks'.
  ENDMETHOD.

ENDCLASS.
