CLASS zcl_lab_38_prod_price_mb DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA price TYPE string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_lab_38_prod_price_mb IMPLEMENTATION.
ENDCLASS.
